apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-logging-collector-binding
subjects:
  - kind: ServiceAccount
    name: collector
    namespace: openshift-logging
roleRef:
  kind: ClusterRole
  name: cluster-logging-collector
  apiGroup: rbac.authorization.k8s.io