apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tempo-operator
  namespace: observability
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: tempo-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace