apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: dev-collector
  namespace: observability
spec:
  config:
    receivers:
      jaeger:
        protocols:
          grpc: {}
          thrift_http: {}
      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:
      batch: {}

    exporters:
      otlp:
        endpoint: tempo-simplest-gateway.observability.svc:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [jaeger, otlp]
          processors: [batch]
          exporters: [otlp]