apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: dev-collector
spec:
  config:
    receivers:
      jaeger:
        protocols:
          grpc:
          thrift_http:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch: {}
    exporters:
      debug: {}
    service:
      pipelines:
        traces:
          receivers: [jaeger, otlp]
          processors: [batch]
          exporters: [debug]