apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
  namespace: observability
spec:
  storage:
    secret:
      name: tempo-s3-credentials
      type: s3
    tls:
      enabled: true
      caName: openshift-service-ca.crt
  storageSize: 1Gi
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: "2000m"
  template:
    gateway:
      enabled: false
    queryFrontend:
      jaegerQuery:
        enabled: true