apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
  namespace: observability
spec:
  storage:
    secret:
      name: tempo-s3-credentials
      type: s3
  template:
    distributor:
      tls:
        enabled: false
    gateway:
      enabled: true
    queryFrontend:
      jaegerQuery:
        enabled: true