apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: noobaa-obc-provisioner
  namespace: observability
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: noobaa-obc-provisioner-binding
  namespace: observability
subjects:
- kind: ServiceAccount
  name: noobaa-operator
  namespace: openshift-storage
roleRef:
  kind: Role
  name: noobaa-obc-provisioner
  apiGroup: rbac.authorization.k8s.io