apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  manageNodes: false
  storageDeviceSets:
  - name: ocs-deviceset-sno
    count: 1
    replica: 1
    resources: {}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: gp3-csi
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 250Gi