apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    ocs.openshift.io/on-single-node: "true"
spec:
  manageNodes: false
  monPVCTemplate:
    spec:
      storageClassName: gp3-csi
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  storageDeviceSets:
  - name: ocs-deviceset-sno
    count: 1
    replica: 1
    placement:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    dataPVCTemplate:
      spec:
        storageClassName: gp3-csi
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 250Gi