apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  flexibleScaling: true
  manageNodes: false
  resourceProfile: lean
  monDataDirHostPath: /var/lib/rook
  storageDeviceSets:
    - name: ocs-deviceset-gp3
      count: 1
      replica: 1
      resources: {}
      placement: {}
      dataPVCTemplate:
        spec:
          storageClassName: gp3-csi
          accessModes:
            - ReadWriteOnce
          volumeMode: Block
          resources:
            requests:
              storage: 250Gi