---
- name: "Create ArgoCD application for ODF MCG instance (StorageSystem)"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: odf-mcg-instance
        namespace: openshift-gitops
      spec:
        project: default
        source: { repoURL: "{{ gitops_repo }}", targetRevision: main, path: apps/odf-mcg/overlays/dev }
        destination: { server: https://kubernetes.default.svc }
        syncPolicy: { automated: { prune: true, selfHeal: true } }
        ignoreDifferences:
        - group: ocs.openshift.io
          kind: StorageCluster
          name: ocs-storagecluster
          namespace: openshift-storage
          jsonPointers:
          - /metadata/ownerReferences